[workspace]
resolver = "2"
members = [
    "core",
    "tui",
    "cli",
    "src-tauri",
]

[workspace.package]
version = "0.6.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/y-tretyakov/portarium"
homepage = "https://github.com/y-tretyakov/portarium"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
color-eyre = "0.6"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
once_cell = "1"
toml = "0.8"
sysinfo = "0.30"
libc = "0.2"
